FROM python:3.9-slim 
RUN apt-get update && apt-get install -y wget openjdk-17-jre-headless graphviz 
RUN wget -O /plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2023.12/plantuml-1.2023.12.jar 
